import StoreProvider from "@/components/StoreProvider";
import { store } from "@/store/store";
import type { Metadata } from "next";
import { Provider } from "react-redux";

export const metadata: Metadata = {
  title: "Kanban",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body style={{ background: "#20212c" }}>{children}</body>
      </StoreProvider>
    </html>
  );
}
